/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ChucVuController;
import controller.NhanVienController;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChucVu;
import model.NhanVien;

/**
 *
 * @author ASUS
 */
public class FormQuanLyNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form FormQuanLyNhanVien
     */
    ArrayList<NhanVien> dsnv;
    ArrayList<ChucVu> dscv;
    public FormQuanLyNhanVien() {
        initComponents();
        this.setLocationRelativeTo(null);
        hienThiLenTable();
        ChucVuController chucVuController=new ChucVuController();
                dscv=chucVuController.docChucVu();
        for (ChucVu o : dscv) {
            cmbChucVu.addItem(o.getChucvu());
        }
        btnCapNhatChucVu.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableQuanLyNhanVien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JFormattedTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSTK = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtChamCong = new javax.swing.JTextField();
        radioNam = new javax.swing.JRadioButton();
        radioNu = new javax.swing.JRadioButton();
        cmbChucVu = new javax.swing.JComboBox<>();
        btnLuuChamCong = new javax.swing.JButton();
        btnCapNhatChucVu = new javax.swing.JButton();
        btnXemLuong = new javax.swing.JButton();
        btnTroVe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableQuanLyNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Ngày Sinh", "Địa Chỉ", "Giới Tính", "STK", "SDT", "Email", "Chức Vụ", "Chấm Công", "Đi làm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableQuanLyNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableQuanLyNhanVien);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tên");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Giới Tính");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ngày Sinh");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("STK");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Chức Vụ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Địa Chỉ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("SDT");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Chấm Công");

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtNgaySinh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtSTK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtChamCong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        buttonGroup1.add(radioNam);
        radioNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radioNam.setText("Nam");

        buttonGroup1.add(radioNu);
        radioNu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radioNu.setText("Nữ");

        cmbChucVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnLuuChamCong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLuuChamCong.setText("Lưu Chấm Công");
        btnLuuChamCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuChamCongActionPerformed(evt);
            }
        });

        btnCapNhatChucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCapNhatChucVu.setText("Cập nhập chức vụ");
        btnCapNhatChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatChucVuActionPerformed(evt);
            }
        });

        btnXemLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXemLuong.setText("Xem lương");
        btnXemLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemLuongActionPerformed(evt);
            }
        });

        btnTroVe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTroVe.setText("Trở về");
        btnTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioNam)
                        .addGap(18, 18, 18)
                        .addComponent(radioNu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(txtTen))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnXemLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCapNhatChucVu)
                        .addGap(75, 75, 75)
                        .addComponent(btnLuuChamCong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTroVe)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSTK)
                            .addComponent(cmbChucVu, 0, 158, Short.MAX_VALUE)
                            .addComponent(txtNgaySinh))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(txtSDT)
                            .addComponent(txtChamCong))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txtSTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioNam)
                    .addComponent(radioNu))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(txtChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuuChamCong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXemLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCapNhatChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableQuanLyNhanVienMouseClicked
        // TODO add your handling code here:
        btnCapNhatChucVu.setEnabled(true);
        int row = tableQuanLyNhanVien.getSelectedRow();
        String ten=tableQuanLyNhanVien.getValueAt(row, 1).toString();
        String ngaysinh=tableQuanLyNhanVien.getValueAt(row, 2).toString();
        String diachi=tableQuanLyNhanVien.getValueAt(row, 3).toString();
        String gioitinh=tableQuanLyNhanVien.getValueAt(row, 4).toString();
        String stk=tableQuanLyNhanVien.getValueAt(row, 5).toString();
        String sdt=tableQuanLyNhanVien.getValueAt(row, 6).toString();
        String email=tableQuanLyNhanVien.getValueAt(row, 7).toString();
        String chucvu=tableQuanLyNhanVien.getValueAt(row, 8).toString();
        String chamcong=tableQuanLyNhanVien.getValueAt(row, 9).toString();
        
        txtTen.setText(ten);
        txtTen.setCaretPosition(0);
        txtNgaySinh.setText(ngaysinh);
        txtDiaChi.setText(diachi);
        txtDiaChi.setCaretPosition(0);
        if(gioitinh.equalsIgnoreCase("Nam")){
            radioNam.setSelected(true);
        }else{
            radioNu.setSelected(true); 
        }txtSTK.setText(stk);
        txtSTK.setCaretPosition(0);
        txtSDT.setText(sdt);
        txtSDT.setCaretPosition(0);
        txtEmail.setText(email);
        txtEmail.setCaretPosition(0);
        cmbChucVu.setSelectedItem(chucvu);
        txtChamCong.setText(chamcong);
        
        txtTen.setEditable(false);
        txtNgaySinh.setEditable(false);
        txtDiaChi.setEditable(false);
        txtSTK.setEditable(false);
        txtSDT.setEditable(false);
        txtEmail.setEditable(false);
        radioNam.setEnabled(false);
        radioNu.setEnabled(false);
        txtChamCong.setEditable(false);
    }//GEN-LAST:event_tableQuanLyNhanVienMouseClicked

    private void btnLuuChamCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuChamCongActionPerformed
        // TODO add your handling code here:
        NhanVienController nvController = new NhanVienController();
       // int r= tableQuanLyNhanVien.getSelectedRow();
        for(int  i=0;i<tableQuanLyNhanVien.getRowCount();i++){
            String maNv= (String) tableQuanLyNhanVien.getValueAt(i, 0).toString();
            int chamCong= ((int) tableQuanLyNhanVien.getValueAt(i, 9)+(Boolean.TRUE.equals(tableQuanLyNhanVien.getValueAt(i, 10))?1:0));
            nvController.chamCongNhanVien(chamCong, maNv);
        }
        JOptionPane.showMessageDialog(this, "Chấm công thành công", "Thông báo", 1);
        
        hienThiLenTable();
        
    }//GEN-LAST:event_btnLuuChamCongActionPerformed

    private void btnCapNhatChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatChucVuActionPerformed
        // TODO add your handling code here:
        NhanVienController nvController = new NhanVienController();
         int r= tableQuanLyNhanVien.getSelectedRow();
         String maNv= (String) tableQuanLyNhanVien.getValueAt(r, 0).toString();
         String chucVu=cmbChucVu.getSelectedItem().toString();
         nvController.capNhatNhanVien(chucVu, maNv);
         JOptionPane.showMessageDialog(this, "Cập nhật thành công ", "Thông báo", 1);
         hienThiLenTable();

    }//GEN-LAST:event_btnCapNhatChucVuActionPerformed

    private void btnTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnTroVeActionPerformed

    private void btnXemLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemLuongActionPerformed
        // TODO add your handling code here:
        FormXemLuong formXemLuong=new FormXemLuong();
        formXemLuong.setVisible(true);
        this.dispose();
        formXemLuong.addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
            new FormQuanLyNhanVien().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_btnXemLuongActionPerformed

    public void hienThiLenTable(){
        String vaitro="User";
        NhanVienController nvController=new NhanVienController();
        dsnv=nvController.docNhanVien(vaitro);
        DefaultTableModel model = (DefaultTableModel)tableQuanLyNhanVien.getModel();
        model.setRowCount(0);
//        for(int i=0;i<dsnv.size();i++){
//            
//        }
        for (NhanVien o : dsnv) {
            model.addRow(new Object[]{
                o.getMaNV(),
                o.getTen(),
                o.getNgaySinh(),
                o.getDiaChi(),
                o.getGioiTinh(),
                o.getSTK(),
                o.getSDT(),
                o.getEmail(),
                o.getChucVu(),
                o.getChamCong()
            });
        }
        btnCapNhatChucVu.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatChucVu;
    private javax.swing.JButton btnLuuChamCong;
    private javax.swing.JButton btnTroVe;
    private javax.swing.JButton btnXemLuong;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioNu;
    private javax.swing.JTable tableQuanLyNhanVien;
    private javax.swing.JTextField txtChamCong;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSTK;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
