/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ChucVuController;
import controller.NhanVienController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChucVu;
import model.NhanVien;

/**
 *
 * @author ASUS
 */
public class FormXemLuong extends javax.swing.JFrame {

    /**
     * Creates new form FormXemLuong
     */
    ArrayList<NhanVien> dsnv;
    ArrayList<ChucVu> dscv;
    public FormXemLuong() {
        initComponents();
        this.setLocationRelativeTo(null);
        getData();
        txtTen.setEditable(false);
        txtChucVu.setEditable(false);
        txtLuong.setEditable(false);
        txtSTK.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTraLuong = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtSTK = new javax.swing.JTextField();
        txtChucVu = new javax.swing.JTextField();
        txtLuong = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnTraLuong = new javax.swing.JButton();
        btnTroVe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableTraLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Tên", "Ngày sinh", "SDT", "Chức vụ", "Số công", "Hệ số lương", "Lương", "Trả lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTraLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTraLuongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTraLuong);
        if (tableTraLuong.getColumnModel().getColumnCount() > 0) {
            tableTraLuong.getColumnModel().getColumn(0).setMinWidth(45);
            tableTraLuong.getColumnModel().getColumn(0).setMaxWidth(45);
            tableTraLuong.getColumnModel().getColumn(7).setMinWidth(90);
            tableTraLuong.getColumnModel().getColumn(7).setMaxWidth(90);
            tableTraLuong.getColumnModel().getColumn(8).setMinWidth(60);
            tableTraLuong.getColumnModel().getColumn(8).setMaxWidth(60);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tên");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("STK");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Chức vụ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Lương");

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtSTK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtChucVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnTraLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTraLuong.setText("Trả lương");
        btnTraLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraLuongActionPerformed(evt);
            }
        });

        btnTroVe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTroVe.setText("Trở về");
        btnTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnTraLuong)
                .addGap(18, 18, 18)
                .addComponent(btnTroVe, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTraLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(txtSTK)
                    .addComponent(txtTen)
                    .addComponent(txtLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableTraLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTraLuongMouseClicked
        // TODO add your handling code here:
        int row=tableTraLuong.getSelectedRow();
        String ten=tableTraLuong.getValueAt(row, 0).toString().trim();
        String stk=tableTraLuong.getValueAt(row, 3).toString().trim();
        String chucVu=tableTraLuong.getValueAt(row, 4).toString().trim();
        String luong=tableTraLuong.getValueAt(row, 7).toString();
        
        txtTen.setText(ten);
        txtSTK.setText(stk);
        txtChucVu.setText(chucVu);
        txtLuong.setText(luong);
    }//GEN-LAST:event_tableTraLuongMouseClicked

    private void btnTraLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraLuongActionPerformed
        // TODO add your handling code here:
        int tk = JOptionPane.showConfirmDialog(null, "Bạn có chắc là đã trả lương cho họ rồi chứ? ","Trả lương",JOptionPane.YES_OPTION);
      if (tk==JOptionPane.YES_OPTION){
          NhanVienController nvController = new NhanVienController();
        for(int  i=0;i<tableTraLuong.getRowCount();i++){
            String maNv= tableTraLuong.getValueAt(i, 0).toString();
            int chamCong = (Boolean.TRUE.equals(tableTraLuong.getValueAt(i, 8))) ? 0 : (int) tableTraLuong.getValueAt(i, 5);
            nvController.chamCongNhanVien(chamCong, maNv);
        }
        JOptionPane.showMessageDialog(this, "Trả lương hoàn tất", "Thông báo", 1);
      }
      getData();
        
        
    }//GEN-LAST:event_btnTraLuongActionPerformed

    private void btnTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnTroVeActionPerformed

    private void getData(){
        String VaiTro="User";
        NhanVienController nvController=new NhanVienController();
        dsnv=nvController.docNhanVien(VaiTro);
        DefaultTableModel model = (DefaultTableModel) tableTraLuong.getModel();
        model.setRowCount(0);
        ChucVuController cvController=new ChucVuController();
        dscv=cvController.docChucVu();

        for(NhanVien o:dsnv){
            
            float heSoLuong=0;
            for(ChucVu cv:dscv){
                if(cv.getChucvu().equals(o.getChucVu())){
                    heSoLuong=cv.getHeSoLuong();
                    break;
                }
            }
            model.addRow(new Object[]{
                o.getMaNV(),
            o.getTen(),
            o.getNgaySinh(),
            o.getSTK(),
            o.getChucVu(),
            o.getChamCong(),
            heSoLuong,
            o.getChamCong()*heSoLuong
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormXemLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormXemLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormXemLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormXemLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormXemLuong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTraLuong;
    private javax.swing.JButton btnTroVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTraLuong;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtSTK;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
