/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ChucVuController;
import controller.NhanVienController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChucVu;

/**
 *
 * @author ASUS
 */
public class FormQuanLyChucVu extends javax.swing.JFrame {

    /**
     * Creates new form FormQuanLyChucVu
     */
    ArrayList<ChucVu> dscv;
    public FormQuanLyChucVu() {
        initComponents();
        this.setLocationRelativeTo(null);
        getDuLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableChucVu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JTextField();
        txtHeSoLuong = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chức vụ", "Hệ số lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableChucVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableChucVu);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Chức vụ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Hệ số lương");

        txtChucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtHeSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(txtHeSoLuong)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi)
                    .addComponent(btnSua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableChucVuMouseClicked
        // TODO add your handling code here:
        int row=tableChucVu.getSelectedRow();
        String chucVu=tableChucVu.getValueAt(row, 0).toString();
        String heSoLuong=tableChucVu.getValueAt(row, 1).toString();
        Float hsl=Float.valueOf(heSoLuong);
        
        txtChucVu.setText(chucVu);
        txtChucVu.setCaretPosition(0);
        txtHeSoLuong.setText(Float.toString(hsl));
        
        if(row==0){
        btnThem.setEnabled(false);
        btnSua.setEnabled(false);
        txtChucVu.setEditable(false);
        btnXoa.setEnabled(false);
        txtHeSoLuong.setEditable(false);
        }else{
            btnThem.setEnabled(false);
        btnSua.setEnabled(true);
        txtChucVu.setEditable(false);
        btnXoa.setEnabled(true);
        txtHeSoLuong.setEditable(true);
        }
    }//GEN-LAST:event_tableChucVuMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtChucVu.setText("");
        txtHeSoLuong.setText("");
        txtChucVu.setEditable(true);
        btnThem.setEnabled(true);
        getDuLieu();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String chucVu=txtChucVu.getText().toString().trim();
        int loiChucVu=0;
        for(int i=0;i<tableChucVu.getRowCount()-1;i++){
            if(tableChucVu.getValueAt(i, 0).toString().trim().equalsIgnoreCase(chucVu)){
                loiChucVu++;
            }
        }
        if(chucVu.equals("")){
            loiChucVu++;
        }
        Float heSoLuong=null;
        int loiHeSoLuong=0;
        try {
            heSoLuong=Float.valueOf(txtHeSoLuong.getText());
        } catch (Exception e) {
            loiHeSoLuong++;
        }
        ChucVuController cvController=new ChucVuController();
        if(loiHeSoLuong==0){
            
            if(loiChucVu==0){
                if(cvController.themChucVu(chucVu, heSoLuong)>0){
                JOptionPane.showMessageDialog(this, "Thêm mới thành công","Chúc mừng",1);
                getDuLieu();
                }else{
                JOptionPane.showMessageDialog(this, "Thêm mới thất bại", "Rất tiếc", 1);
                }
            }else{
                 JOptionPane.showMessageDialog(this, "Chức vụ này có vẻ đã tồn tại", "Thông báo", 1);
            }  
        }else{
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số thực vào ô hệ số lương", "Thông báo", 1);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String chucVu=txtChucVu.getText().toString().trim();
        Float heSoLuong=null;
        int loiHeSoLuong=0;
        try {
            heSoLuong=Float.valueOf(txtHeSoLuong.getText());
        } catch (Exception e) {
            loiHeSoLuong++;
        }
        ChucVuController cvController=new ChucVuController();
        if(loiHeSoLuong==0){
            if(cvController.suaChucVu(chucVu, heSoLuong)>0){
                JOptionPane.showMessageDialog(this, "Sửa thành công","Chúc mừng",1);
                getDuLieu();
            }else{
                JOptionPane.showMessageDialog(this, "Sửa thất bại", "Rất tiếc", 1);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số thực vào ô hệ số lương", "Thông báo", 1);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:\
        String chucVu=txtChucVu.getText().toString().trim();
        int tk = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa '"+chucVu+ "' không?","Xóa",JOptionPane.YES_OPTION);
        if(tk==JOptionPane.YES_OPTION){
            NhanVienController nvController=new NhanVienController();
            ChucVuController cvController=new ChucVuController();
            nvController.xoaChucVuNhanVien(chucVu);
            if(cvController.xoaChucVu(chucVu)>0){
                JOptionPane.showMessageDialog(this, "Xóa thành công\n Bạn cần vào mục Quản lý nhân viên để đổi Chức vụ cho các nhân viên từng có chức vụ vừa bị xóa", "Thành công", 1);
                getDuLieu();
            }else{
                JOptionPane.showMessageDialog(this, "Xóa thất bại", "Rất tiếc", 1);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLyChucVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableChucVu;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtHeSoLuong;
    // End of variables declaration//GEN-END:variables

    private void getDuLieu() {
        ChucVuController cvController=new ChucVuController();
        dscv=cvController.docChucVu();
        DefaultTableModel model = (DefaultTableModel)tableChucVu.getModel();
        model.setRowCount(0);
        for(ChucVu o:dscv){
            model.addRow(new Object[]{
                o.getChucvu(),
                o.getHeSoLuong()
            });
        }
        txtChucVu.setText("");
        txtHeSoLuong.setText("");
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }
}
