/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ChucVuController;
import controller.NguoiDungController;
import controller.NhanVienController;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChucVu;
import model.NguoiDung;
import model.NhanVien;

/**
 *
 * @author ASUS
 */
public class FormQuanLyTaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form FormQuanLyTaiKhoan
     */
    ArrayList<ChucVu> dscv;
    ArrayList<NguoiDung> dsnd;
    NguoiDung nd;
   // ArrayList<NhanVien> docNV;
    public FormQuanLyTaiKhoan() {
        initComponents();
        this.setLocationRelativeTo(null);
        getDuLieu();
        btnXoaTaiKhoan.setEnabled(false);
        ChucVuController chucVuController=new ChucVuController();
                dscv=chucVuController.docChucVu();
        for (ChucVu o : dscv) {
            cmbChucVu.addItem(o.getChucvu());
        }
        chuyenDoi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableQuanLyTaiKhoan = new javax.swing.JTable();
        btnThemTaiKhoan = new javax.swing.JButton();
        btnXoaTaiKhoan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        radioAdmin = new javax.swing.JRadioButton();
        radioUser = new javax.swing.JRadioButton();
        txtTenDangNhap = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSTK = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMaND = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JFormattedTextField();
        txtSDT = new javax.swing.JTextField();
        radioNam = new javax.swing.JRadioButton();
        radioNu = new javax.swing.JRadioButton();
        btnLamMoi = new javax.swing.JButton();
        cmbChucVu = new javax.swing.JComboBox<>();
        btnTroVe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tableQuanLyTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaND", "Tên đăng nhập", "Mật khẩu", "Vai trò"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableQuanLyTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableQuanLyTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableQuanLyTaiKhoan);
        if (tableQuanLyTaiKhoan.getColumnModel().getColumnCount() > 0) {
            tableQuanLyTaiKhoan.getColumnModel().getColumn(0).setMinWidth(60);
            tableQuanLyTaiKhoan.getColumnModel().getColumn(0).setMaxWidth(60);
            tableQuanLyTaiKhoan.getColumnModel().getColumn(3).setMinWidth(75);
            tableQuanLyTaiKhoan.getColumnModel().getColumn(3).setMaxWidth(75);
        }

        btnThemTaiKhoan.setText("Thêm Tài Khoản");
        btnThemTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTaiKhoanActionPerformed(evt);
            }
        });

        btnXoaTaiKhoan.setText("Xóa tài Khoản");
        btnXoaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTaiKhoanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("MaNV");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Địa chỉ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("STK");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("MaND");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ngày sinh");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Giới tính");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("SDT");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Chức vụ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Tìm tên");

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Tên đăng nhập");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Mật khẩu");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Vai trò");

        buttonGroup1.add(radioAdmin);
        radioAdmin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioAdmin.setText("Admin");

        buttonGroup1.add(radioUser);
        radioUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioUser.setSelected(true);
        radioUser.setText("User");

        txtTenDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtSTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMaND.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNgaySinh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buttonGroup2.add(radioNam);
        radioNam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioNam.setSelected(true);
        radioNam.setText("Nam");

        buttonGroup2.add(radioNu);
        radioNu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioNu.setText("Nữ");

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnTroVe.setText("Trở về");
        btnTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoi)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(32, 32, 32)
                                        .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(btnTim)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(radioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioUser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel3)
                                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(85, 85, 85)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(txtMaNV)
                                                                    .addComponent(txtTen)
                                                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(txtSTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel7))
                                                            .addGap(6, 6, 6))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(18, 18, 18))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnThemTaiKhoan)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnXoaTaiKhoan)
                                                .addGap(6, 6, 6)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaND, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(radioNam, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(radioNu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnTroVe)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(cmbChucVu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))))
                                .addGap(47, 47, 47))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioAdmin)
                    .addComponent(radioUser))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioNam)
                    .addComponent(radioNu))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(txtSTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chuyenDoi(){
        String giaTri= tableQuanLyTaiKhoan.getValueAt(tableQuanLyTaiKhoan.getRowCount()-1, 0).toString().trim();
        // int mand=Integer.parseInt(giaTri);
        //System.out.println("dong so:"+ (tableQuanLyTaiKhoan.getRowCount()-1));
        //System.out.println("gia tri cua dong do:"+tableQuanLyTaiKhoan.getValueAt(tableQuanLyTaiKhoan.getRowCount()-1, 0).toString());
        
        int mand = 0;
        try {
        mand = Integer.parseInt(giaTri);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ồ, không thể chuyển đổi sang số nguyên, vui lòng liên hệ với nhà phát triển");
        }
       // System.out.println(mand);
        mand+=1;
        String mAnd=Integer.toString(mand);
        txtMaND.setText(mAnd);
        txtMaNV.setText("NV0"+mAnd);
    }
    private void getDuLieu(){
        NguoiDungController ndController = new NguoiDungController();
        dsnd=ndController.hienThiNguoiDung();
        DefaultTableModel model = (DefaultTableModel)tableQuanLyTaiKhoan.getModel();
        model.setRowCount(0);
        for(NguoiDung o:dsnd){
            model.addRow(new Object[]{
                o.getMaND(),
                o.getTenDangNhap(),
                o.getMatKhau(),
                o.getVaiTro()
            });
        }
        txtMaND.setEditable(false);
        txtMaNV.setEditable(false);
    }
    private void tableQuanLyTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableQuanLyTaiKhoanMouseClicked
        // TODO add your handling code here:
        int row=tableQuanLyTaiKhoan.getSelectedRow();
        String maND = tableQuanLyTaiKhoan.getValueAt(row, 0).toString();
        String tenDangNhap=tableQuanLyTaiKhoan.getValueAt(row, 1).toString();
        String matkhau = tableQuanLyTaiKhoan.getValueAt(row, 2).toString();
        String vaiTro = tableQuanLyTaiKhoan.getValueAt(row, 3).toString();
        
        txtMaND.setText(maND);
        txtTenDangNhap.setText(tenDangNhap);
        txtMatKhau.setText(matkhau);
        if(vaiTro.trim().equalsIgnoreCase("Admin")){
            radioAdmin.setSelected(true);
        }else{
            radioUser.setSelected(true);
        }
        txtMaND.setCaretPosition(0);
        txtTenDangNhap.setCaretPosition(0);
        txtMatKhau.setCaretPosition(0);
        
        NhanVienController nvController= new NhanVienController();
        ArrayList<NhanVien> docNV = nvController.docNvTheoMaND(maND);
        txtMaNV.setText(docNV.get(0).getMaNV());
        txtTen.setText(docNV.get(0).getTen());
        txtNgaySinh.setText(docNV.get(0).getNgaySinh());
        txtDiaChi.setText(docNV.get(0).getDiaChi());
        String gioiTinh=docNV.get(0).getGioiTinh();
        if(gioiTinh.trim().equalsIgnoreCase("Nam")){
            radioNam.setSelected(true);
        }else{
            radioNu.setSelected(true);
        }
        txtSTK.setText(docNV.get(0).getSTK());
        txtSDT.setText(docNV.get(0).getSDT());
        txtEmail.setText(docNV.get(0).getEmail());
        cmbChucVu.setSelectedItem(docNV.get(0).getChucVu());
        
        txtTen.setCaretPosition(0);
        txtNgaySinh.setCaretPosition(0);
        txtDiaChi.setCaretPosition(0);
        txtSTK.setCaretPosition(0);
        txtSDT.setCaretPosition(0);
        txtMatKhau.setCaretPosition(0);
        txtEmail.setCaretPosition(0);
        
        txtMaND.setEditable(false);
        txtTenDangNhap.setEditable(false);
        txtMatKhau.setEditable(false);
        txtMaNV.setEditable(false);
        radioAdmin.setEnabled(false);
        radioUser.setEnabled(false);
        
        btnThemTaiKhoan.setEnabled(false);
        txtTen.setEditable(false);
        txtNgaySinh.setEditable(false);
        txtDiaChi.setEditable(false);
        txtSTK.setEditable(false);
        txtSDT.setEditable(false);
        txtMatKhau.setEditable(false);
        txtEmail.setEditable(false);
//        cmbChucVu.setEditable(false);
        radioNam.setEnabled(false);
        radioNu.setEnabled(false);
        
        if(txtMaND.getText().trim().equalsIgnoreCase(nd.getMaND().trim())){
            btnXoaTaiKhoan.setEnabled(false);
        }else{
            btnXoaTaiKhoan.setEnabled(true);
        }
        

    }//GEN-LAST:event_tableQuanLyTaiKhoanMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowOpened

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        NguoiDungController ndController = new NguoiDungController();
        String ten = txtTim.getText().trim();
        ArrayList<NguoiDung> timND = ndController.timKiemNguoiDung(ten);
        DefaultTableModel model = (DefaultTableModel)tableQuanLyTaiKhoan.getModel();
        model.setRowCount(0);
        for(NguoiDung o:timND){
            model.addRow(new Object[]{
                o.getMaND(),
                o.getTenDangNhap(),
                o.getMatKhau(),
                o.getVaiTro()
            });
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
                
        txtTim.setText("");
        txtMaND.setEditable(false);
        txtTenDangNhap.setEditable(true);
        txtMatKhau.setEditable(true);
        txtMaNV.setEditable(false);
        radioAdmin.setEnabled(true);
        radioUser.setEnabled(true);
        
        btnThemTaiKhoan.setEnabled(true);
        txtTen.setEditable(true);
        txtNgaySinh.setEditable(true);
        txtDiaChi.setEditable(true);
        txtSTK.setEditable(true);
        txtSDT.setEditable(true);
        txtMatKhau.setEditable(true);
        txtEmail.setEditable(true);
//        cmbChucVu.setEditable(true);

        radioNam.setEnabled(true);
        radioNu.setEnabled(true);
        
       // txtMaND.setText("");
        txtTenDangNhap.setText("");
        txtMatKhau.setText("");
        //txtMaNV.setText("");

        txtTen.setText("");
        txtNgaySinh.setText("");
        txtDiaChi.setText("");
        txtSTK.setText("");
        txtSDT.setText("");
        txtMatKhau.setText("");
        txtEmail.setText("");
        getDuLieu();
        
        btnXoaTaiKhoan.setEnabled(false);
        
        chuyenDoi();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTaiKhoanActionPerformed
        // TODO add your handling code here:
        
        int loiNgaySinh=0;
        int loiTenTaiKhoan=0;
        int loiMatKhau=0;
        
        NhanVienController nvController=new NhanVienController();
        NguoiDungController ndController=new NguoiDungController();
        
        String MaND= txtMaND.getText();
        String TenDangNhap=txtTenDangNhap.getText();
        String MatKhau=txtMatKhau.getText();
        String MaNV=txtMaNV.getText();
        
        for(int i=0;i<tableQuanLyTaiKhoan.getRowCount()-1;i++){
            String tenDangnhap = tableQuanLyTaiKhoan.getValueAt(i, 1).toString().trim();
            if(TenDangNhap.trim().equals("")||TenDangNhap.trim().equals(tenDangnhap)){
                loiTenTaiKhoan++;
            }
        }
        if(MatKhau.trim().equals("")){
            loiMatKhau++;
        }
        if(loiTenTaiKhoan!=0){
            JOptionPane.showMessageDialog(this, "Tên tài khoản rỗng hoặc đã tồn tại","Thông báo",1);
            loiTenTaiKhoan=0;
        }else{
            if(loiMatKhau!=0){
                JOptionPane.showMessageDialog(this, "Mật khẩu rỗng, vui lòng nhập mật khẩu","Thông báo",1);
                loiMatKhau=0;
            }else{
                
        String VaiTro=null;
        if(radioAdmin.isSelected()){
            VaiTro="Admin";
        }else{
             VaiTro="User";
        }
        
        String Ten= txtTen.getText();
        String ngaysinh=txtNgaySinh.getText();
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date NgaySinh = null;
        try {
            NgaySinh = dateFormat.parse(ngaysinh);
        } catch (ParseException ex) {
            //Logger.getLogger(FormSuaThongTinAdmin.class.getName()).log(Level.SEVERE, null, ex);
            loiNgaySinh++;
        }
        String DiaChi=txtDiaChi.getText();
        String STK=txtSTK.getText();
        String SDT=txtSDT.getText();
        String Email=txtEmail.getText();
        String ChucVu=cmbChucVu.getSelectedItem().toString();
        String GioiTinh=null;
        if(radioNam.isSelected()){
             GioiTinh="Nam";
        }else{
             GioiTinh="Nữ";
        }
                if(loiNgaySinh!=0){
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày sinh theo định dạng (ngày/tháng/năm).\nVD:04/10/2003","Thông báo",1);
                }else{
                    if(ndController.themNguoiDung(MaND, TenDangNhap, MatKhau, VaiTro)>0&&nvController.themNhanVien(MaNV, MaND, Ten, NgaySinh, DiaChi, GioiTinh, STK, SDT, Email, ChucVu)>0){
                    JOptionPane.showMessageDialog(this, "Thêm Thành Công","Thông báo",1);   
                    getDuLieu();
                    }else{
                        JOptionPane.showMessageDialog(this, "Thêm Thất Bại","Thông báo",0);
                    }
                }
            }
        }
        

    }//GEN-LAST:event_btnThemTaiKhoanActionPerformed

    private void btnXoaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTaiKhoanActionPerformed
        // TODO add your handling code here:
        int index=tableQuanLyTaiKhoan.getSelectedRow();
        NguoiDungController ndController=new NguoiDungController();
         int tk = JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa '"+txtTen.getText().trim()+ "' không?","Xóa",JOptionPane.YES_OPTION);
      if (tk==JOptionPane.YES_OPTION)  
      {
        if (ndController.xoaNguoiDung(tableQuanLyTaiKhoan.getValueAt(index,0).toString()))
        {
            JOptionPane.showMessageDialog(this, "Xóa tài khoản thành công", "Thông Báo", 1);
            getDuLieu();
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi hệ thống", "Thông Báo", 0);
        }
        
      }
      else
      {
          return; 
      }
    }//GEN-LAST:event_btnXoaTaiKhoanActionPerformed

    private void btnTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnTroVeActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuanLyTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThemTaiKhoan;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTroVe;
    private javax.swing.JButton btnXoaTaiKhoan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmbChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioAdmin;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioNu;
    private javax.swing.JRadioButton radioUser;
    private javax.swing.JTable tableQuanLyTaiKhoan;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaND;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JFormattedTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSTK;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenDangNhap;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
